version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nft_marketplace
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  backend:
    build: ./back-end
    environment:
      DATABASE_URL: postgres://yourusername:yourpassword@db:5432/yourdatabase
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./front-end
    environment:
      VITE_BACKEND_URL: http://backend:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db_data:

