name: nft_marketplace

services:
  db:
    image: postgres:13
    container_name: nft_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nft_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - nft_network

  backend:
    build:
      context: ./back-end
    container_name: nft_backend
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/nft_db
      API_PORT: 5000
      FRONTEND_ORIGIN: http://localhost:5173
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - nft_network

  frontend:
    build:
      context: ./front-end
    container_name: nft_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - nft_network
    command: yarn dev --host

networks:
  nft_network: {}

volumes:
  db_data: {}
