[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
nft_marketplace = "hPd5fM2UuWmU36aE1Cx3HmhScY9fWFswVwe53R2HWZs"

[programs.localnet]
nft_marketplace = "hPd5fM2UuWmU36aE1Cx3HmhScY9fWFswVwe53R2HWZs"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "tests/metaplex_token_metadata_program.so"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./localnet-payer.json"

[scripts]
test = "yarn run ts-mocha -n loader=ts-node/esm -p tsconfig.json tests/**/*.ts"
